unplace_cell  [get_cells -hierarchical -filter {((NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/PCIe_Bridge_ICAP_complex_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gtye4_top.PCIe_Bridge_ICAP_complex_xdma_0_0_pcie4_ip_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[*].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[*].GTYE4_CHANNEL_PRIM_INST) && (is_primitive==true && primitive_level!="INTERNAL")  && (loc!=""))}]
set_property LOC AP2   [get_ports pcie_mgt_rxp[0]]
set_property LOC AR4   [get_ports pcie_mgt_rxp[1]]
set_property LOC AT2   [get_ports pcie_mgt_rxp[2]]
set_property LOC AU4   [get_ports pcie_mgt_rxp[3]]
set_property LOC AV2   [get_ports pcie_mgt_rxp[4]]
set_property LOC AW4   [get_ports pcie_mgt_rxp[5]]
set_property LOC BA2   [get_ports pcie_mgt_rxp[6]]
set_property LOC BC2   [get_ports pcie_mgt_rxp[7]]
set_property LOC AF2   [get_ports pcie_mgt_rxp[8]]
set_property LOC AG4   [get_ports pcie_mgt_rxp[9]]
set_property LOC AH2   [get_ports pcie_mgt_rxp[10]]
set_property LOC AJ4   [get_ports pcie_mgt_rxp[11]]
set_property LOC AK2   [get_ports pcie_mgt_rxp[12]]
set_property LOC AL4   [get_ports pcie_mgt_rxp[13]]
set_property LOC AM2   [get_ports pcie_mgt_rxp[14]]
set_property LOC AN4   [get_ports pcie_mgt_rxp[15]]


set_property LOC AP7   [get_ports pcie_mgt_txp[0]]
set_property LOC AR9   [get_ports pcie_mgt_txp[1]]
set_property LOC AT7   [get_ports pcie_mgt_txp[2]]
set_property LOC AU9   [get_ports pcie_mgt_txp[3]]
set_property LOC AV7   [get_ports pcie_mgt_txp[4]]
set_property LOC BB5   [get_ports pcie_mgt_txp[5]]
set_property LOC BD5   [get_ports pcie_mgt_txp[6]]
set_property LOC BF5   [get_ports pcie_mgt_txp[7]]
set_property LOC AF7   [get_ports pcie_mgt_txp[8]]
set_property LOC AG9   [get_ports pcie_mgt_txp[9]]
set_property LOC AH7   [get_ports pcie_mgt_txp[10]]
set_property LOC AJ9   [get_ports pcie_mgt_txp[11]]
set_property LOC AK7   [get_ports pcie_mgt_txp[12]]
set_property LOC AL9   [get_ports pcie_mgt_txp[13]]
set_property LOC AM7   [get_ports pcie_mgt_txp[14]]
set_property LOC AN9   [get_ports pcie_mgt_txp[15]]

set_property LOC GTYE4_CHANNEL_X1Y28 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[29].*gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y29 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[29].*gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y30 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[29].*gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y31 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[29].*gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y32 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[30].*gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y33 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[30].*gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y34 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[30].*gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y35 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[30].*gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y20 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[31].*gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y21 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[31].*gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y22 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[31].*gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y23 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[31].*gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y24 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[32].*gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y25 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[32].*gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y26 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[32].*gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property LOC GTYE4_CHANNEL_X1Y27 [get_cells -hierarchical -filter {NAME =~ *PCIe_Bridge_ICAP_complex_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.*gen_channel_container[32].*gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]


