include ../../Make_common_pre
#NUMBER_OF_CU := 1

DESIGN_NAME := passthru
SRCS_HOST  +=  ../src/tb_passthru.cpp
SRCS_XOCC  :=   ../src/sdx_cppKernel_top.cpp ../src/kernel_WRAPPER.cpp ../src/passthru.cpp ../src/sdx_cppKernel_top.cpp

include ../../Make_common_post

