include ../../Make_common_pre
#NUMBER_OF_CU := 1

DESIGN_NAME := fp_vector_mult
SRCS_HOST  +=  ../src/tb_fp_vector_mult.cpp
SRCS_XOCC  :=  ../src/sdx_cppKernel_top.cpp ../src/kernel_WRAPPER.cpp ../src/floating_point_vector_mult.cpp

include ../../Make_common_post

