include ../../Make_common_pre
#NUMBER_OF_CU := 1

DESIGN_NAME := matrix_inv_5x5
SRCS_HOST  +=  ../src/tb_matrix_inv_5x5_north.cpp 
SRCS_XOCC  :=  ../src/sdx_cppKernel_top.cpp ../src/kernel_WRAPPER.cpp ../src/matrix_operation_wrapper.cpp

include ../../Make_common_post

